import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div className='flex'>
        {/* sidebar */}

        {/* client notifier */}

        <div className='bg-[#343541] flex-1'> {children}</div>
       </div>
        </body>
    </html>
  )
}
